- name: Slack Notification
  uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_MESSAGE: 'QA Automation report'
        SLACK_TITLE: qa
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}